#!/usr/bin/env bash
#
# Cross-repo KV contract parity: the only check that can see BOTH repos.
#
# `build_kv_content()` in qr_backend produces the `content` blob that the Worker in
# qr_cf_code renders from at scan time. They are independent git repos, so the backend's
# tests can only assert its output against expectations written in qr_backend, and the
# Worker's tests can only assert its readers against fixtures written in qr_cf_code — two
# hand-written fakes of each other, free to drift with nothing to notice. That seam is
# where "the QR saves fine but the scan page is blank / stale / falls back" comes from.
#
# The fix is the same one already used for i18n keys.json: ONE canonical artefact,
# generated by the backend from the real function, copied into the Worker repo, and diffed
# here. `kv_contract.json` is that artefact.
#
# This is a MANUAL pre-merge step. It is not CI, because no CI job in this monorepo sees
# both repos.
#
#   ./scripts/check-kv-contract-parity.sh
#
# Exit 0 = the two repos agree. Exit 1 = they do not, and the diff shows what to reconcile.

set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
backend_contract="$root/qr_backend/tests/integration_tests/kv_contract.json"
worker_contract="$root/qr_cf_code/src/integration/kv_contract.json"

for f in "$backend_contract" "$worker_contract"; do
    if [[ ! -f "$f" ]]; then
        echo "error: missing $f" >&2
        echo "generate it with: cd qr_backend && UPDATE_KV_CONTRACT=1 pytest tests/integration_tests/test_kv_contract.py" >&2
        exit 1
    fi
done

# Compared semantically rather than byte-wise so key order and indentation cannot cause a
# spurious failure — only an actual shape or value difference should fail this.
normalise() {
    python3 -c '
import json, sys
print(json.dumps(json.load(open(sys.argv[1])), ensure_ascii=False, indent=2, sort_keys=True))
' "$1"
}

if ! diff -u \
    --label "qr_backend/tests/integration_tests/kv_contract.json" \
    --label "qr_cf_code/src/integration/kv_contract.json" \
    <(normalise "$backend_contract") <(normalise "$worker_contract"); then
    cat >&2 <<'MSG'

^^ KV contract disagrees between the repos.

The backend is the generator; the Worker copy is downstream. Reconcile by regenerating
and copying, never by hand-editing the Worker's copy:

  cd qr_backend
  UPDATE_KV_CONTRACT=1 pytest tests/integration_tests/test_kv_contract.py
  cp tests/integration_tests/kv_contract.json ../qr_cf_code/src/integration/

Then re-run both sides:

  cd qr_backend  && pytest tests/integration_tests/test_kv_contract.py
  cd qr_cf_code  && node src/integration/kvContract.test.mjs
MSG
    exit 1
fi

types=$(python3 -c 'import json,sys; print(len(json.load(open(sys.argv[1]))))' "$backend_contract")
echo "KV contract parity OK — $types QR types agree across both repos."
